[package]
name = "crmprs"
authors = ["Rafael Ortiz <rafael.ortiz@redcanary.com>"]
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crc64 = "1.0.0"
clap = "2.33.3"
